
import { StateLaw } from './types';

export const STATE_LAWS: Record<string, StateLaw> = {
  AL: { code: 'AL', name: 'Alabama', deadlineDays: 60, multiplier: 2.0, statute: 'Ala. Code § 35-9A-201' },
  AK: { code: 'AK', name: 'Alaska', deadlineDays: 14, multiplier: 2.0, statute: 'Alaska Stat. § 34.03.070' },
  AZ: { code: 'AZ', name: 'Arizona', deadlineDays: 14, multiplier: 3.0, statute: 'Ariz. Rev. Stat. § 33-1321' },
  AR: { code: 'AR', name: 'Arkansas', deadlineDays: 60, multiplier: 2.0, statute: 'Ark. Code § 18-16-305' },
  CA: { code: 'CA', name: 'California', deadlineDays: 21, multiplier: 2.0, statute: 'Cal. Civ. Code § 1950.5' },
  CO: { code: 'CO', name: 'Colorado', deadlineDays: 30, multiplier: 3.0, statute: 'Colo. Rev. Stat. § 38-12-103' },
  CT: { code: 'CT', name: 'Connecticut', deadlineDays: 30, multiplier: 2.0, statute: 'Conn. Gen. Stat. § 47a-21' },
  DE: { code: 'DE', name: 'Delaware', deadlineDays: 20, multiplier: 2.0, statute: '25 Del. Code § 5514' },
  FL: { code: 'FL', name: 'Florida', deadlineDays: 30, multiplier: 1.0, statute: 'Fla. Stat. § 83.49' },
  GA: { code: 'GA', name: 'Georgia', deadlineDays: 30, multiplier: 3.0, statute: 'Ga. Code § 44-7-34' },
  HI: { code: 'HI', name: 'Hawaii', deadlineDays: 14, multiplier: 3.0, statute: 'Haw. Rev. Stat. § 521-44' },
  ID: { code: 'ID', name: 'Idaho', deadlineDays: 21, multiplier: 3.0, statute: 'Idaho Code § 6-321' },
  IL: { code: 'IL', name: 'Illinois', deadlineDays: 45, multiplier: 2.0, statute: '765 ILCS 710' },
  IN: { code: 'IN', name: 'Indiana', deadlineDays: 45, multiplier: 1.0, statute: 'Ind. Code § 32-31-3-12' },
  IA: { code: 'IA', name: 'Iowa', deadlineDays: 30, multiplier: 2.0, statute: 'Iowa Code § 562A.12' },
  KS: { code: 'KS', name: 'Kansas', deadlineDays: 30, multiplier: 1.5, statute: 'Kan. Stat. § 58-2550' },
  KY: { code: 'KY', name: 'Kentucky', deadlineDays: 30, multiplier: 1.0, statute: 'Ky. Rev. Stat. § 383.580' },
  LA: { code: 'LA', name: 'Louisiana', deadlineDays: 30, multiplier: 2.0, statute: 'La. Rev. Stat. § 9:3251' },
  ME: { code: 'ME', name: 'Maine', deadlineDays: 21, multiplier: 2.0, statute: '14 Me. Rev. Stat. § 6033' },
  MD: { code: 'MD', name: 'Maryland', deadlineDays: 45, multiplier: 3.0, statute: 'Md. Code, Real Prop. § 8-203' },
  MA: { code: 'MA', name: 'Massachusetts', deadlineDays: 30, multiplier: 3.0, statute: 'Mass. Gen. Laws ch. 186, § 15B' },
  MI: { code: 'MI', name: 'Michigan', deadlineDays: 30, multiplier: 2.0, statute: 'Mich. Comp. Laws § 554.607' },
  MN: { code: 'MN', name: 'Minnesota', deadlineDays: 21, multiplier: 2.0, statute: 'Minn. Stat. § 504B.178' },
  MS: { code: 'MS', name: 'Mississippi', deadlineDays: 45, multiplier: 1.0, statute: 'Miss. Code § 89-8-21' },
  MO: { code: 'MO', name: 'Missouri', deadlineDays: 30, multiplier: 2.0, statute: 'Mo. Rev. Stat. § 535.300' },
  MT: { code: 'MT', name: 'Montana', deadlineDays: 30, multiplier: 1.0, statute: 'Mont. Code § 70-25-202' },
  NE: { code: 'NE', name: 'Nebraska', deadlineDays: 14, multiplier: 1.0, statute: 'Neb. Rev. Stat. § 76-1416' },
  NV: { code: 'NV', name: 'Nevada', deadlineDays: 30, multiplier: 1.0, statute: 'Nev. Rev. Stat. § 118A.242' },
  NH: { code: 'NH', name: 'New Hampshire', deadlineDays: 30, multiplier: 2.0, statute: 'N.H. Rev. Stat. § 540-A:7' },
  NJ: { code: 'NJ', name: 'New Jersey', deadlineDays: 30, multiplier: 2.0, statute: 'N.J. Stat. § 46:8-21.1' },
  NM: { code: 'NM', name: 'New Mexico', deadlineDays: 30, multiplier: 1.0, statute: 'N.M. Stat. § 47-8-18' },
  NY: { code: 'NY', name: 'New York', deadlineDays: 14, multiplier: 2.0, statute: 'NY GOB § 7-108' },
  NC: { code: 'NC', name: 'North Carolina', deadlineDays: 30, multiplier: 1.0, statute: 'N.C. Gen. Stat. § 42-52' },
  ND: { code: 'ND', name: 'North Dakota', deadlineDays: 30, multiplier: 3.0, statute: 'N.D. Cent. Code § 47-16-07.1' },
  OH: { code: 'OH', name: 'Ohio', deadlineDays: 30, multiplier: 2.0, statute: 'Ohio Rev. Code § 5321.16' },
  OK: { code: 'OK', name: 'Oklahoma', deadlineDays: 45, multiplier: 2.0, statute: 'Okla. Stat. tit. 41, § 115' },
  OR: { code: 'OR', name: 'Oregon', deadlineDays: 31, multiplier: 2.0, statute: 'Or. Rev. Stat. § 90.300' },
  PA: { code: 'PA', name: 'Pennsylvania', deadlineDays: 30, multiplier: 2.0, statute: '68 Pa. Stat. § 250.512' },
  RI: { code: 'RI', name: 'Rhode Island', deadlineDays: 20, multiplier: 2.0, statute: 'R.I. Gen. Laws § 34-18-19' },
  SC: { code: 'SC', name: 'South Carolina', deadlineDays: 30, multiplier: 3.0, statute: 'S.C. Code § 27-40-410' },
  SD: { code: 'SD', name: 'South Dakota', deadlineDays: 14, multiplier: 1.0, statute: 'S.D. Codified Laws § 43-32-24' },
  TN: { code: 'TN', name: 'Tennessee', deadlineDays: 30, multiplier: 1.0, statute: 'Tenn. Code § 66-28-301' },
  TX: { code: 'TX', name: 'Texas', deadlineDays: 30, multiplier: 3.0, statute: 'Texas Prop. Code § 92.103' },
  UT: { code: 'UT', name: 'Utah', deadlineDays: 30, multiplier: 1.0, statute: 'Utah Code § 57-17-3' },
  VT: { code: 'VT', name: 'Vermont', deadlineDays: 14, multiplier: 1.0, statute: '9 Vt. Stat. § 4461' },
  VA: { code: 'VA', name: 'Virginia', deadlineDays: 45, multiplier: 1.0, statute: 'Va. Code § 55.1-1226' },
  WA: { code: 'WA', name: 'Washington', deadlineDays: 30, multiplier: 2.0, statute: 'RCW 59.18.280' },
  WV: { code: 'WV', name: 'West Virginia', deadlineDays: 60, multiplier: 1.0, statute: 'W. Va. Code § 37-6A-2' },
  WI: { code: 'WI', name: 'Wisconsin', deadlineDays: 21, multiplier: 2.0, statute: 'Wis. Stat. § 704.28' },
  WY: { code: 'WY', name: 'Wyoming', deadlineDays: 30, multiplier: 1.0, statute: 'Wyo. Stat. § 1-21-1208' }
};

export const LOB_CERTIFIED_FEE = 29.00;
