
export const generatePDF = (text: string, filename: string = 'demand_letter.pdf', signatureData?: string) => {
  const { jsPDF } = (window as any).jspdf;
  
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'letter'
  });
  
  // Professional serif font
  doc.setFont("times", "normal");
  doc.setFontSize(12);
  
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  const margin = 25.4; // Standard 1-inch margins
  const maxLineWidth = pageWidth - (margin * 2);
  
  // Metadata for the PDF
  doc.setProperties({
    title: 'Formal Demand for Security Deposit',
    subject: 'Legal Correspondence',
    author: 'The Deposit Retriever',
    creator: 'The Deposit Retriever AI Service'
  });

  const splitText = doc.splitTextToSize(text, maxLineWidth);
  let cursorY = margin + 10; // Start slightly lower than top margin
  const lineHeight = 7.5;

  splitText.forEach((line: string) => {
    // Page break handling
    if (cursorY > pageHeight - margin - (signatureData ? 40 : 10)) {
      doc.addPage();
      cursorY = margin;
    }
    
    // Check for bold headers (like SUBJECT: or SENDER:)
    if (line.includes(':') && line.length < 50 && (line === line.toUpperCase() || line.startsWith('SUBJECT:'))) {
       doc.setFont("times", "bold");
       doc.text(line, margin, cursorY);
       doc.setFont("times", "normal");
    } else {
       doc.text(line, margin, cursorY);
    }
    
    cursorY += lineHeight;
  });

  // Digital Signature Block
  if (signatureData) {
    const sigWidth = 50;
    const sigHeight = 15;
    
    // Add some space before signature
    cursorY += 10;
    
    if (cursorY + sigHeight + 10 > pageHeight - margin) {
      doc.addPage();
      cursorY = margin;
    }

    try {
      doc.addImage(signatureData, 'PNG', margin, cursorY, sigWidth, sigHeight);
      cursorY += sigHeight + 5;
      doc.setFontSize(9);
      doc.setFont("times", "italic");
      doc.text("Electronically Signed by Tenant", margin, cursorY);
      
      const today = new Date().toLocaleDateString();
      doc.text(`Date: ${today}`, margin, cursorY + 5);
    } catch (e) {
      console.error("PDF Signature Error", e);
    }
  }

  // Add footer to every page
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 20, pageHeight - 10);
    doc.text("Generated by The Deposit Retriever Legal Tech Service", margin, pageHeight - 10);
  }
  
  doc.save(filename);
};
